#!/usr/bin/env python3
"""Build canvas_data.json + file_contents.json for the agnostic canvas viewer.

Walks docs/, reads each markdown file's YAML frontmatter, groups files into
clusters by folder, computes a Layered Column-Tree layout per the canvas
documentation specification, and emits two JSON artefacts the viewer loads
at runtime:

- canvas_data.json: { project_metadata, nodes[], edges[] }
- file_contents.json: { "<relative path>": { title, type, tags, status, content } }

Run from the Project Ganymede repo root:

    python scripts/build_canvas.py
    python scripts/build_canvas.py --output-dir "../ganymede docs/ganymede-viewer/public"

Defaults to writing into the viewer's public/ folder so Vite serves the
JSON at the root URL during dev.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DOCS_DIR = Path("docs")

# `ganymede docs` lives in the user's Desktop, three levels up from this repo
# (Desktop / GANYMEDE_FINAL / PROJECT_GANYMEDE / Project Ganymede).
DEFAULT_OUTPUT_DIR = (
    Path("..") / ".." / ".." / "ganymede docs" / "ganymede-viewer" / "public"
)

NODE_WIDTH = 280
NODE_HEIGHT = 80
HORIZONTAL_SPACING = 380
VERTICAL_SPACING = 120
ROW_START_Y = 220
HUB_Y = 0


# Top-level folder → (display label, color_id) for cluster ordering.
# Order here determines column ordering in the canvas.
CLUSTER_ORDER: list[tuple[str, str, str]] = [
    ("foundations", "Core Framework", "4"),
    ("concepts", "Concepts", "5"),
    ("experiments/pathways", "Pathways", "3"),
    ("experiments/runs", "Experimental Runs", "1"),
    ("protocols", "Protocols", "6"),
    ("integration", "Integration", "2"),
    ("history", "History", "6"),
    ("learnings", "Learnings", "6"),
    ("visions", "Visions", "3"),
    ("brainstorming", "Brainstorming", "1"),
]


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Return (frontmatter_dict, body) parsed from a markdown file's text.

    Frontmatter is the YAML-shaped block bounded by `---` lines at the top
    of the file. We do a minimal, key-by-key parse since the frontmatter is
    well-controlled (generated by scripts/add_frontmatter.py).
    """
    if not (text.startswith("---\n") or text.startswith("---\r\n")):
        return {}, text

    # Find the closing --- line.
    lines = text.splitlines(keepends=True)
    if not lines:
        return {}, text

    end_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}, text

    fm_lines = lines[1:end_idx]
    body = "".join(lines[end_idx + 1:])
    # Drop a single leading blank line in the body if present.
    if body.startswith("\n"):
        body = body[1:]
    elif body.startswith("\r\n"):
        body = body[2:]

    fm: dict = {}
    for line in fm_lines:
        m = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*?)\s*$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2)
        fm[key] = parse_yaml_value(raw)
    return fm, body


def parse_yaml_value(raw: str):
    """Parse a single YAML scalar/list value (limited to our generated shape)."""
    raw = raw.strip()
    if not raw:
        return ""
    # List form: [ "a", "b", ... ]
    if raw.startswith("["):
        m = re.match(r"^\[(.*)\]$", raw)
        if m:
            inner = m.group(1).strip()
            if not inner:
                return []
            items = [s.strip() for s in split_top_level_commas(inner)]
            return [strip_quotes(item) for item in items]
    return strip_quotes(raw)


def split_top_level_commas(s: str) -> list[str]:
    """Split on commas not inside quotes."""
    out: list[str] = []
    buf: list[str] = []
    in_quote = False
    quote_char = ""
    for ch in s:
        if in_quote:
            buf.append(ch)
            if ch == quote_char:
                in_quote = False
            continue
        if ch in ('"', "'"):
            in_quote = True
            quote_char = ch
            buf.append(ch)
            continue
        if ch == ",":
            out.append("".join(buf))
            buf = []
            continue
        buf.append(ch)
    if buf:
        out.append("".join(buf))
    return out


def strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return s[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return s


def slugify(s: str) -> str:
    """Make an id-safe slug from a path or label."""
    out = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return out or "node"


def find_cluster_for(rel_path: Path) -> tuple[str, str, str] | None:
    """Return (cluster_key, label, color_id) for a doc relative to docs/, or None."""
    posix = rel_path.as_posix()
    parent = rel_path.parent.as_posix()

    best: tuple[str, str, str] | None = None
    best_len = -1
    for key, label, color in CLUSTER_ORDER:
        if parent == key or parent.startswith(key + "/"):
            if len(key) > best_len:
                best = (key, label, color)
                best_len = len(key)
    return best


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Directory to write canvas_data.json + file_contents.json (default: {DEFAULT_OUTPUT_DIR}).",
    )
    args = parser.parse_args()

    if not DOCS_DIR.is_dir():
        raise SystemExit(
            f"docs/ not found in {Path.cwd()} — run from the Project Ganymede repo root"
        )

    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Walk docs/ and parse frontmatter.
    docs: list[dict] = []
    for path in sorted(DOCS_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)
        rel = path.relative_to(DOCS_DIR)
        docs.append(
            {
                "path": rel.as_posix(),
                "frontmatter": fm,
                "body": body,
                "is_root": rel.parent.as_posix() in (".", ""),
                "filename": path.name,
            }
        )

    # 2. Identify the hub (OVERVIEW.md at root; fall back to README.md).
    hub_doc = next((d for d in docs if d["path"] == "OVERVIEW.md"), None)
    if hub_doc is None:
        hub_doc = next((d for d in docs if d["path"] == "README.md"), None)
    if hub_doc is None:
        raise SystemExit("No OVERVIEW.md or README.md at docs/ root — cannot pick a hub node")

    # 3. Group non-hub docs by cluster. Anything that isn't in a CLUSTER_ORDER
    #    cluster becomes "hub-attached misc" (root-level docs + orphan nested docs).
    cluster_index: dict[str, list[dict]] = {key: [] for key, _, _ in CLUSTER_ORDER}
    hub_attached: list[dict] = []
    for d in docs:
        if d["path"] == hub_doc["path"]:
            continue
        if d["is_root"]:
            hub_attached.append(d)
            continue
        cluster = find_cluster_for(Path(d["path"]))
        if cluster is None:
            hub_attached.append(d)
            continue
        cluster_index[cluster[0]].append(d)

    # 4. Compute layout coordinates.
    columns = [(key, label, color, cluster_index[key]) for key, label, color in CLUSTER_ORDER if cluster_index[key]]
    num_columns = len(columns)
    total_width = max(0, (num_columns - 1) * HORIZONTAL_SPACING)

    nodes: list[dict] = []
    edges: list[dict] = []

    # Hub node centred above the cluster columns.
    hub_x = total_width / 2 - NODE_WIDTH / 2
    hub_id = "hub"
    hub_color = hub_doc["frontmatter"].get("color_id", "4")
    nodes.append(
        {
            "id": hub_id,
            "x": hub_x,
            "y": HUB_Y,
            "width": NODE_WIDTH,
            "height": NODE_HEIGHT,
            "type": "file",
            "file": hub_doc["path"],
            "color": hub_color,
        }
    )

    # Each cluster as a column. Cluster head (folder README.md) in row 1; child files below.
    for col_idx, (key, label, color, docs_in_cluster) in enumerate(columns):
        col_x = col_idx * HORIZONTAL_SPACING

        # Sort: README.md first (cluster head), then numeric prefixes, then alphabetic.
        def sort_key(d):
            fname = d["filename"]
            if fname.lower() == "readme.md":
                return (0, "")
            m = re.match(r"^(\d+)", fname)
            if m:
                return (1, int(m.group(1)), fname.lower())
            return (2, fname.lower())

        docs_in_cluster.sort(key=sort_key)

        cluster_head_doc = None
        children = docs_in_cluster
        if docs_in_cluster and docs_in_cluster[0]["filename"].lower() == "readme.md":
            cluster_head_doc = docs_in_cluster[0]
            children = docs_in_cluster[1:]

        cluster_head_id = f"cluster-{slugify(key)}"
        cluster_head_y = ROW_START_Y
        if cluster_head_doc is not None:
            nodes.append(
                {
                    "id": cluster_head_id,
                    "x": col_x,
                    "y": cluster_head_y,
                    "width": NODE_WIDTH,
                    "height": NODE_HEIGHT,
                    "type": "file",
                    "file": cluster_head_doc["path"],
                    "color": color,
                    "label": label,
                }
            )
        else:
            # Synthesised label-only cluster head.
            nodes.append(
                {
                    "id": cluster_head_id,
                    "x": col_x,
                    "y": cluster_head_y,
                    "width": NODE_WIDTH,
                    "height": NODE_HEIGHT,
                    "type": "label",
                    "label": label,
                    "color": color,
                }
            )

        edges.append(
            {
                "id": f"e-hub-{cluster_head_id}",
                "fromNode": hub_id,
                "fromSide": "bottom",
                "toNode": cluster_head_id,
                "toSide": "top",
            }
        )

        # Children stacked vertically.
        for child_idx, child in enumerate(children):
            child_y = cluster_head_y + (child_idx + 1) * VERTICAL_SPACING
            child_id = f"node-{slugify(child['path'])}"
            child_color = child["frontmatter"].get("color_id", color)
            nodes.append(
                {
                    "id": child_id,
                    "x": col_x,
                    "y": child_y,
                    "width": NODE_WIDTH,
                    "height": NODE_HEIGHT,
                    "type": "file",
                    "file": child["path"],
                    "color": child_color,
                }
            )
            edges.append(
                {
                    "id": f"e-{cluster_head_id}-{child_id}",
                    "fromNode": cluster_head_id,
                    "fromSide": "bottom",
                    "toNode": child_id,
                    "toSide": "top",
                }
            )

    # Hub-attached misc docs (root-level + orphan nested). Half go left of the hub,
    # half go right, both stacked vertically alongside the hub at y=HUB_Y and just below.
    hub_attached.sort(key=lambda d: d["path"].lower())
    if hub_attached:
        left_count = len(hub_attached) // 2
        for idx, d in enumerate(hub_attached):
            node_id = f"hubchild-{slugify(d['path'])}"
            if idx < left_count:
                # Left of hub.
                offset = left_count - idx
                node_x = hub_x - offset * HORIZONTAL_SPACING
                from_side = "left"
                to_side = "right"
            else:
                # Right of hub.
                offset = idx - left_count + 1
                node_x = hub_x + offset * HORIZONTAL_SPACING
                from_side = "right"
                to_side = "left"
            nodes.append(
                {
                    "id": node_id,
                    "x": node_x,
                    "y": HUB_Y,
                    "width": NODE_WIDTH,
                    "height": NODE_HEIGHT,
                    "type": "file",
                    "file": d["path"],
                    "color": d["frontmatter"].get("color_id", "4"),
                }
            )
            edges.append(
                {
                    "id": f"e-hub-{node_id}",
                    "fromNode": hub_id,
                    "fromSide": from_side,
                    "toNode": node_id,
                    "toSide": to_side,
                }
            )

    # 5. Build file_contents.json from frontmatter + body.
    file_contents: dict[str, dict] = {}
    for d in docs:
        fm = d["frontmatter"]
        file_contents[d["path"]] = {
            "title": fm.get("title", d["filename"]),
            "type": fm.get("type", "concept"),
            "tags": fm.get("tags", []) if isinstance(fm.get("tags"), list) else [],
            "status": fm.get("status", "active"),
            "content": d["body"],
        }

    # 6. Assemble canvas_data.json.
    canvas_data = {
        "project_metadata": {
            "name": "Project Ganymede",
            "domain": "9D Strategic-Physics",
            "version": "2026-05-25",
            "hub_file": hub_doc["path"],
        },
        "nodes": nodes,
        "edges": edges,
    }

    # 7. Write outputs.
    canvas_path = output_dir / "canvas_data.json"
    file_contents_path = output_dir / "file_contents.json"

    canvas_path.write_text(
        json.dumps(canvas_data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    file_contents_path.write_text(
        json.dumps(file_contents, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {canvas_path} ({len(nodes)} nodes, {len(edges)} edges)")
    print(f"Wrote {file_contents_path} ({len(file_contents)} docs)")

    # Sanity: print cluster summary.
    print("\nCluster summary:")
    for key, label, _, docs_in_cluster in columns:
        print(f"  {key:35s} -> {len(docs_in_cluster):3d} files  ({label})")
    if hub_attached:
        print(f"  {'(hub-attached misc)':35s} -> {len(hub_attached):3d} files")


if __name__ == "__main__":
    main()
