export const layers = {
  evidence: { number: '01', title: 'Evidence' },
  time: { number: '02', title: 'Time' },
  incentives: { number: '03', title: 'Incentives' },
  constraints: { number: '04', title: 'Constraints' },
  people: { number: '05', title: 'People' },
  systems: { number: '06', title: 'Systems' },
  uncertainty: { number: '07', title: 'Uncertainty' },
  countermove: { number: '08', title: 'Countermove' },
  'second-order': { number: '09', title: 'Second order' },
};

export const scenarios = {
  water: {
    title: 'Water under pressure',
    question: 'Can a desert community keep groundwater use within a sustainable range while demand continues to grow?',
    core: 'Sustainable balance',
    subtitle: 'What changes the outcome?',
    frame: 'Separate present pumping, future demand, recharge, and policy response instead of treating the trend as a straight line.',
    hypothesis: 'Without enforceable reductions, demand is likely to outpace replenishment.',
    audit: 'The first answer overweights the headline depletion rate and assumes every planned restriction will work as written.',
    revision: 'The outcome depends less on one forecast than on monitoring, compliance, and whether reductions arrive before new demand.',
    confidence: 74,
    confidenceNote: 'Strong direction, but policy compliance and local recharge remain meaningful unknowns.',
    layers: {
      evidence: 'Measurements show the direction of travel, but well coverage and reporting cadence determine how much confidence they deserve.',
      time: 'Demand grows gradually while policy and infrastructure arrive in steps. The order of those events matters.',
      incentives: 'Large users save money by delaying reductions; residents bear costs that are spread across the basin.',
      constraints: 'Recharge, existing water rights, monitoring capacity, and enforcement place hard limits on the available choices.',
      people: 'Households, farms, industry, and tribal communities experience the same aquifer through very different risks.',
      systems: 'Water use, land development, pricing, and regulation reinforce one another instead of moving independently.',
      uncertainty: 'Future growth and local recharge are ranges, not fixed numbers. The conclusion should remain conditional.',
      countermove: 'A major user may change timing, accounting, or sourcing when restrictions begin to bind.',
      'second-order': 'A successful restriction can shift pumping elsewhere, change land values, or accelerate conservation investment.',
    },
  },
  library: {
    title: 'A library after dark',
    question: 'Should a neighborhood library stay open later when evening access is valuable but staffing and safety budgets are limited?',
    core: 'Useful access',
    subtitle: 'Who benefits, and at what cost?',
    frame: 'Treat evening access, staffing, transportation, safety, and alternative services as one connected decision.',
    hypothesis: 'Two later evenings each week could create most of the access benefit without a full schedule change.',
    audit: 'The first answer assumes demand is evenly distributed and treats safety as a fixed expense rather than a design question.',
    revision: 'Pilot the hours on the two highest-demand evenings, coordinate transit and partner programming, then publish the evidence used to continue or stop.',
    confidence: 82,
    confidenceNote: 'A reversible pilot creates useful evidence without pretending the first schedule is permanent.',
    layers: {
      evidence: 'Door counts, program attendance, computer use, and neighborhood surveys reveal different kinds of demand.',
      time: 'The valuable window may be the two hours after work and school, not an equally long extension every night.',
      incentives: 'Partners gain a venue, staff absorb schedule changes, and patrons gain access they cannot use during work hours.',
      constraints: 'Staffing agreements, transit frequency, security coverage, and the building budget shape the feasible pilot.',
      people: 'Students, shift workers, unhoused neighbors, parents, staff, and nearby residents need different things from late access.',
      systems: 'Library hours interact with buses, schools, social services, and community programming.',
      uncertainty: 'Survey enthusiasm may not become attendance. A pilot turns that uncertainty into observable behavior.',
      countermove: 'If attendance concentrates around one program, the library can redesign the offer instead of defending empty hours.',
      'second-order': 'Later hours may strengthen partner programs and neighborhood trust even when book circulation barely changes.',
    },
  },
  launch: {
    title: 'A careful launch',
    question: 'How should a small team release an experimental tool without presenting early results as more certain than they are?',
    core: 'Credible release',
    subtitle: 'How can learning remain honest?',
    frame: 'Separate what the software demonstrates today from what its underlying method still needs to prove.',
    hypothesis: 'A demonstration edition with recorded examples is more honest than opening account-bound experimental machinery.',
    audit: 'The first answer risks making caution look like secrecy and does not give visitors enough material to evaluate the work.',
    revision: 'Publish the inspectable interface, architecture, examples, limitations, and license while keeping private accounts and unfinished integrations outside the release.',
    confidence: 89,
    confidenceNote: 'The release boundary is clear, reversible, and gives readers enough evidence to judge the idea.',
    layers: {
      evidence: 'Working interactions, tests, screenshots, and explicit limitations support claims better than a broad promise.',
      time: 'A public snapshot should remain understandable after the private research system changes underneath it.',
      incentives: 'The creator wants legible portfolio evidence; visitors need an honest object they can inspect and run.',
      constraints: 'Private accounts, historical baggage, external documents, and unfinished migrations do not belong in a clean release.',
      people: 'Curious visitors, prospective employers, researchers, and future contributors arrive with different levels of context.',
      systems: 'Code, documentation, repository history, licensing, and the public narrative all define the product together.',
      uncertainty: 'The reasoning method remains experimental, so the interface must distinguish a demonstration from validation.',
      countermove: 'A reader may mistake polished presentation for a scientific claim; limitations should be visible before that happens.',
      'second-order': 'A clean public edition can improve the private research project by forcing its interfaces and assumptions to become legible.',
    },
  },
};

